#! /bin/sh
### BEGIN INIT INFO
# Provides:          pishutdown
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Shutdown the Pi using a GPIO pin signal
# Description:       The shutdown_pi.pi python file will run
#                    on startup which will poll the GPIO pin
#                    defined in that file for a signal, once
#                    recieved the python file will execute
#                    shtdown -h now
### END INIT INFO

# Author: Joe Koning <joking@pobox.com>
#

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="Shutdown pi on GPIO signal"
NAME=pishutdown
SCRIPTNAME=/etc/init.d/$NAME
PYSCRIPT=/etc/init.d/shutdown_pi.py


# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

case "$1" in
  start)
        log_action_msg "Starting shutdown_pi.pi"
        $PYSCRIPT &
	;;
  stop)
        log_action_msg "Stop not implemented "
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

:
